name: "Disk Space Reclaimer"
description: "A configurable GitHub Action to reclaim disk space on Ubuntu GitHub Actions runners."
branding:
  icon: "save"
  color: "blue"
inputs:
  android:
    description: "Remove Android runtime"
    required: false
    default: "true"
  dotnet:
    description: "Remove .NET runtime"
    required: false
    default: "true"
  haskell:
    description: "Remove Haskell runtime"
    required: false
    default: "true"
  large-packages:
    description: "Remove large packages"
    required: false
    default: "true"
  tools-cache:
    description: "Remove image tool cache"
    required: false
    default: "false"
  swap-storage:
    description: "Remove swap storage"
    required: false
    default: "true"
  docker-images:
    description: "Remove Docker images"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: "Clean up disk space 🗑️"
      run: bash core.sh
      shell: bash
      env:
        ANDROID: "${{ inputs.android }}"
        DOTNET: "${{ inputs.dotnet }}"
        HASKELL: "${{ inputs.haskell }}"
        LARGE_PACKAGES: "${{ inputs.large-packages }}"
        TOOLS_CACHE: "${{ inputs.tools-cache }}"
        SWAP_STORAGE: "${{ inputs.swap-storage }}"
        DOCKER_IMAGES: "${{ inputs.docker-images }}"
